/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * EmployeeDepartmentView generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`EMPLOYEE_DEPARTMENT_VIEW`")
@IdClass(EmployeeDepartmentViewId.class)
public class EmployeeDepartmentView implements Serializable {

    private Integer employeeId;
    private String firstName;
    private String lastName;
    private String email;
    private String phoneNumber;
    @Type(type = "DateTime")
    private LocalDateTime hireDate;
    private String jobId;
    private Short departmentId;
    private String departmentName;

    @Id
    @Column(name = "`EMPLOYEE_ID`", nullable = false, scale = 0, precision = 6)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Id
    @Column(name = "`FIRST_NAME`", nullable = true, length = 20)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Id
    @Column(name = "`LAST_NAME`", nullable = false, length = 25)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Id
    @Column(name = "`EMAIL`", nullable = false, length = 25)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Id
    @Column(name = "`PHONE_NUMBER`", nullable = false, length = 20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Id
    @Column(name = "`HIRE_DATE`", nullable = false)
    public LocalDateTime getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(LocalDateTime hireDate) {
        this.hireDate = hireDate;
    }

    @Id
    @Column(name = "`JOB_ID`", nullable = false, length = 10)
    public String getJobId() {
        return this.jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    @Id
    @Column(name = "`DEPARTMENT_ID`", nullable = false, scale = 0, precision = 4)
    public Short getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }

    @Id
    @Column(name = "`DEPARTMENT_NAME`", nullable = false, length = 30)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeeDepartmentView)) return false;
        final EmployeeDepartmentView employeeDepartmentView = (EmployeeDepartmentView) o;
        return Objects.equals(getEmployeeId(), employeeDepartmentView.getEmployeeId()) &&
                Objects.equals(getFirstName(), employeeDepartmentView.getFirstName()) &&
                Objects.equals(getLastName(), employeeDepartmentView.getLastName()) &&
                Objects.equals(getEmail(), employeeDepartmentView.getEmail()) &&
                Objects.equals(getPhoneNumber(), employeeDepartmentView.getPhoneNumber()) &&
                Objects.equals(getHireDate(), employeeDepartmentView.getHireDate()) &&
                Objects.equals(getJobId(), employeeDepartmentView.getJobId()) &&
                Objects.equals(getDepartmentId(), employeeDepartmentView.getDepartmentId()) &&
                Objects.equals(getDepartmentName(), employeeDepartmentView.getDepartmentName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeId(),
                getFirstName(),
                getLastName(),
                getEmail(),
                getPhoneNumber(),
                getHireDate(),
                getJobId(),
                getDepartmentId(),
                getDepartmentName());
    }
}

