/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * MandatorycolumnView generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`MANDATORYCOLUMN_VIEW`")
@IdClass(MandatorycolumnViewId.class)
public class MandatorycolumnView implements Serializable {

    private Integer id;
    private String column1;
    private String column3Optional;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`COLUMN1`", nullable = false, length = 255)
    public String getColumn1() {
        return this.column1;
    }

    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    @Id
    @Column(name = "`COLUMN3_OPTIONAL`", nullable = true, length = 255)
    public String getColumn3Optional() {
        return this.column3Optional;
    }

    public void setColumn3Optional(String column3Optional) {
        this.column3Optional = column3Optional;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MandatorycolumnView)) return false;
        final MandatorycolumnView mandatorycolumnView = (MandatorycolumnView) o;
        return Objects.equals(getId(), mandatorycolumnView.getId()) &&
                Objects.equals(getColumn1(), mandatorycolumnView.getColumn1()) &&
                Objects.equals(getColumn3Optional(), mandatorycolumnView.getColumn3Optional());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getColumn1(),
                getColumn3Optional());
    }
}

