/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * SalaryDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SALARY DETAILS`")
public class SalaryDetails implements Serializable {

    private String accountId;
    private BigInteger pfNi;
    private String panNo;
    private Long pay;
    private String isEmployee;
    private Integer userId;
    private Integer userDetails;
    private UserDetails userDetailsByUserDetails;
    private Users users;
    private List<JoiningDetails> joiningDetailses;

    @Id
    @Column(name = "`ACCOUNT ID`", nullable = false, length = 20)
    public String getAccountId() {
        return this.accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    @Column(name = "`PF NI`", nullable = true, scale = 0, precision = 32)
    public BigInteger getPfNi() {
        return this.pfNi;
    }

    public void setPfNi(BigInteger pfNi) {
        this.pfNi = pfNi;
    }

    @Column(name = "`PAN NO`", nullable = true, length = 38)
    public String getPanNo() {
        return this.panNo;
    }

    public void setPanNo(String panNo) {
        this.panNo = panNo;
    }

    @Column(name = "`PAY`", nullable = true, scale = 0, precision = 16)
    public Long getPay() {
        return this.pay;
    }

    public void setPay(Long pay) {
        this.pay = pay;
    }

    @Column(name = "`IS EMPLOYEE`", nullable = true, length = 1)
    public String getIsEmployee() {
        return this.isEmployee;
    }

    public void setIsEmployee(String isEmployee) {
        this.isEmployee = isEmployee;
    }

    @Column(name = "`USER ID`", nullable = true, scale = 0, precision = 7)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "`USER DETAILS`", nullable = true, scale = 0, precision = 10)
    public Integer getUserDetails() {
        return this.userDetails;
    }

    public void setUserDetails(Integer userDetails) {
        this.userDetails = userDetails;
    }

    
    
    public UserDetails getUserDetailsByUserDetails() {
        return this.userDetailsByUserDetails;
    }

    public void setUserDetailsByUserDetails(UserDetails userDetailsByUserDetails) {
        if(userDetailsByUserDetails != null) {
            this.userDetails = userDetailsByUserDetails.getUserDetails();
        }

        this.userDetailsByUserDetails = userDetailsByUserDetails;
    }

    
    
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        if(users != null) {
            this.userId = users.getUserid();
        }

        this.users = users;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<JoiningDetails> getJoiningDetailses() {
        return this.joiningDetailses;
    }

    public void setJoiningDetailses(List<JoiningDetails> joiningDetailses) {
        this.joiningDetailses = joiningDetailses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SalaryDetails)) return false;
        final SalaryDetails salaryDetails = (SalaryDetails) o;
        return Objects.equals(getAccountId(), salaryDetails.getAccountId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAccountId());
    }
}

