/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * ServerdefinedIu generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`serverdefined iu`")
public class ServerdefinedIu implements Serializable {

    private Integer serverdefinedId;
    private String loggedinuserid;
    private String loggedinusername;
    @Type(type = "DateTime")
    private LocalDateTime createdDate;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] userPic;
    private Timestamp createdTime;
    private Timestamp createdDatetime;
    private Integer loggedinuseridInteger;

    @Id
    @Column(name = "`SERVERDEFINED_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getServerdefinedId() {
        return this.serverdefinedId;
    }

    public void setServerdefinedId(Integer serverdefinedId) {
        this.serverdefinedId = serverdefinedId;
    }

    @Column(name = "`LOGGEDINUSERID`", nullable = true, length = 255)
    public String getLoggedinuserid() {
        return this.loggedinuserid;
    }

    public void setLoggedinuserid(String loggedinuserid) {
        this.loggedinuserid = loggedinuserid;
    }

    @Column(name = "`LOGGEDINUSERNAME`", nullable = true, length = 255)
    public String getLoggedinusername() {
        return this.loggedinusername;
    }

    public void setLoggedinusername(String loggedinusername) {
        this.loggedinusername = loggedinusername;
    }

    @Column(name = "`created date`", nullable = true)
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "`user pic`", nullable = true)
    public byte[] getUserPic() {
        return this.userPic;
    }

    public void setUserPic(byte[] userPic) {
        this.userPic = userPic;
    }

    @Column(name = "`created time`", nullable = true)
    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @Column(name = "`created datetime`", nullable = true)
    public Timestamp getCreatedDatetime() {
        return this.createdDatetime;
    }

    public void setCreatedDatetime(Timestamp createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    @Column(name = "`loggedinuserid_Integer`", nullable = true, scale = 0, precision = 10)
    public Integer getLoggedinuseridInteger() {
        return this.loggedinuseridInteger;
    }

    public void setLoggedinuseridInteger(Integer loggedinuseridInteger) {
        this.loggedinuseridInteger = loggedinuseridInteger;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ServerdefinedIu)) return false;
        final ServerdefinedIu serverdefinedIu = (ServerdefinedIu) o;
        return Objects.equals(getServerdefinedId(), serverdefinedIu.getServerdefinedId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getServerdefinedId());
    }
}

