/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShortSequence generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SHORT SEQUENCE`")
public class ShortSequence implements Serializable {

    private Short shortSequence;
    private String status;
    private String name;
    private Integer value;
    private Byte incrementBy;

    @Id
    @Column(name = "`SHORT SEQUENCE`", nullable = false, scale = 0, precision = 5)
    public Short getShortSequence() {
        return this.shortSequence;
    }

    public void setShortSequence(Short shortSequence) {
        this.shortSequence = shortSequence;
    }

    @Column(name = "`STATUS`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`NAME`", nullable = true, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`VALUE`", nullable = true, scale = 0, precision = 6)
    public Integer getValue() {
        return this.value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    @Column(name = "`INCREMENT BY`", nullable = true, scale = 0, precision = 2)
    public Byte getIncrementBy() {
        return this.incrementBy;
    }

    public void setIncrementBy(Byte incrementBy) {
        this.incrementBy = incrementBy;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ShortSequence)) return false;
        final ShortSequence shortSequenceInstance = (ShortSequence) o;
        return Objects.equals(getShortSequence(), shortSequenceInstance.getShortSequence());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShortSequence());
    }
}

