/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.viewsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class NullrecordsviewId implements Serializable {

    private String username;
    private String password;
    private String role;
    private String usernamedeta;
    private Double usersal;
    private Long noofemployees;
    private Boolean isemployee;

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getUsernamedeta() {
        return this.usernamedeta;
    }

    public void setUsernamedeta(String usernamedeta) {
        this.usernamedeta = usernamedeta;
    }

    public Double getUsersal() {
        return this.usersal;
    }

    public void setUsersal(Double usersal) {
        this.usersal = usersal;
    }

    public Long getNoofemployees() {
        return this.noofemployees;
    }

    public void setNoofemployees(Long noofemployees) {
        this.noofemployees = noofemployees;
    }

    public Boolean getIsemployee() {
        return this.isemployee;
    }

    public void setIsemployee(Boolean isemployee) {
        this.isemployee = isemployee;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Nullrecordsview)) return false;
        final Nullrecordsview nullrecordsview = (Nullrecordsview) o;
        return Objects.equals(getUsername(), nullrecordsview.getUsername()) &&
                Objects.equals(getPassword(), nullrecordsview.getPassword()) &&
                Objects.equals(getRole(), nullrecordsview.getRole()) &&
                Objects.equals(getUsernamedeta(), nullrecordsview.getUsernamedeta()) &&
                Objects.equals(getUsersal(), nullrecordsview.getUsersal()) &&
                Objects.equals(getNoofemployees(), nullrecordsview.getNoofemployees()) &&
                Objects.equals(getIsemployee(), nullrecordsview.getIsemployee());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUsername(),
                getPassword(),
                getRole(),
                getUsernamedeta(),
                getUsersal(),
                getNoofemployees(),
                getIsemployee());
    }
}
