/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.viewsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

public class Numberviews1Id implements Serializable {

    private Integer id;
    private Short integerCol;
    private Short shortCol;
    private Integer longCol;
    private Integer bigintegerCol;
    private BigDecimal byteCol;
    private Short floatCol;
    private Double doubleCol;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Short getIntegerCol() {
        return this.integerCol;
    }

    public void setIntegerCol(Short integerCol) {
        this.integerCol = integerCol;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public Integer getLongCol() {
        return this.longCol;
    }

    public void setLongCol(Integer longCol) {
        this.longCol = longCol;
    }

    public Integer getBigintegerCol() {
        return this.bigintegerCol;
    }

    public void setBigintegerCol(Integer bigintegerCol) {
        this.bigintegerCol = bigintegerCol;
    }

    public BigDecimal getByteCol() {
        return this.byteCol;
    }

    public void setByteCol(BigDecimal byteCol) {
        this.byteCol = byteCol;
    }

    public Short getFloatCol() {
        return this.floatCol;
    }

    public void setFloatCol(Short floatCol) {
        this.floatCol = floatCol;
    }

    public Double getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(Double doubleCol) {
        this.doubleCol = doubleCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Numberviews1)) return false;
        final Numberviews1 numberviews1 = (Numberviews1) o;
        return Objects.equals(getId(), numberviews1.getId()) &&
                Objects.equals(getIntegerCol(), numberviews1.getIntegerCol()) &&
                Objects.equals(getShortCol(), numberviews1.getShortCol()) &&
                Objects.equals(getLongCol(), numberviews1.getLongCol()) &&
                Objects.equals(getBigintegerCol(), numberviews1.getBigintegerCol()) &&
                Objects.equals(getByteCol(), numberviews1.getByteCol()) &&
                Objects.equals(getFloatCol(), numberviews1.getFloatCol()) &&
                Objects.equals(getDoubleCol(), numberviews1.getDoubleCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getIntegerCol(),
                getShortCol(),
                getLongCol(),
                getBigintegerCol(),
                getByteCol(),
                getFloatCol(),
                getDoubleCol());
    }
}
