/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.viewsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tableupdate generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLEUpdate`")
public class Tableupdate implements Serializable {

    private Short id;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "\"TABLEUpdate_ID_seq\"" , allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 5)
    public Short getId() {
        return this.id;
    }

    public void setId(Short id) {
        this.id = id;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tableupdate)) return false;
        final Tableupdate tableupdate = (Tableupdate) o;
        return Objects.equals(getId(), tableupdate.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

