/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Time;
import java.util.Objects;

public class ClSchedId implements Serializable {

    private String classCode;
    private Short day;
    private Time starting;
    private Time ending;

    public String getClassCode() {
        return this.classCode;
    }

    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    public Short getDay() {
        return this.day;
    }

    public void setDay(Short day) {
        this.day = day;
    }

    public Time getStarting() {
        return this.starting;
    }

    public void setStarting(Time starting) {
        this.starting = starting;
    }

    public Time getEnding() {
        return this.ending;
    }

    public void setEnding(Time ending) {
        this.ending = ending;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ClSched)) return false;
        final ClSched clSched = (ClSched) o;
        return Objects.equals(getClassCode(), clSched.getClassCode()) &&
                Objects.equals(getDay(), clSched.getDay()) &&
                Objects.equals(getStarting(), clSched.getStarting()) &&
                Objects.equals(getEnding(), clSched.getEnding());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getClassCode(),
                getDay(),
                getStarting(),
                getEnding());
    }
}
