/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Empmdc generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`EMPMDC`")
@IdClass(EmpmdcId.class)
public class Empmdc implements Serializable {

    private Integer empno;
    private Integer dept;
    private Integer div;

    @Id
    @Column(name = "`EMPNO`", nullable = true, scale = 0, precision = 10)
    public Integer getEmpno() {
        return this.empno;
    }

    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    @Id
    @Column(name = "`DEPT`", nullable = true, scale = 0, precision = 10)
    public Integer getDept() {
        return this.dept;
    }

    public void setDept(Integer dept) {
        this.dept = dept;
    }

    @Id
    @Column(name = "`DIV`", nullable = true, scale = 0, precision = 10)
    public Integer getDiv() {
        return this.div;
    }

    public void setDiv(Integer div) {
        this.div = div;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Empmdc)) return false;
        final Empmdc empmdc = (Empmdc) o;
        return Objects.equals(getEmpno(), empmdc.getEmpno()) &&
                Objects.equals(getDept(), empmdc.getDept()) &&
                Objects.equals(getDiv(), empmdc.getDiv());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpno(),
                getDept(),
                getDiv());
    }
}

