/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class OrgId implements Serializable {

    private Short deptnumb;
    private String deptname;
    private Short manager;
    private String division;
    private String location;

    public Short getDeptnumb() {
        return this.deptnumb;
    }

    public void setDeptnumb(Short deptnumb) {
        this.deptnumb = deptnumb;
    }

    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public Short getManager() {
        return this.manager;
    }

    public void setManager(Short manager) {
        this.manager = manager;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Org)) return false;
        final Org org = (Org) o;
        return Objects.equals(getDeptnumb(), org.getDeptnumb()) &&
                Objects.equals(getDeptname(), org.getDeptname()) &&
                Objects.equals(getManager(), org.getManager()) &&
                Objects.equals(getDivision(), org.getDivision()) &&
                Objects.equals(getLocation(), org.getLocation());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDeptnumb(),
                getDeptname(),
                getManager(),
                getDivision(),
                getLocation());
    }
}
