/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Vdept generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`VDEPT`")
@IdClass(VdeptId.class)
public class Vdept implements Serializable {

    private String deptno;
    private String deptname;
    private String mgrno;
    private String admrdept;

    @Id
    @Column(name = "`DEPTNO`", nullable = false, length = 3)
    public String getDeptno() {
        return this.deptno;
    }

    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    @Id
    @Column(name = "`DEPTNAME`", nullable = false, length = 36)
    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    @Id
    @Column(name = "`MGRNO`", nullable = true, length = 6)
    public String getMgrno() {
        return this.mgrno;
    }

    public void setMgrno(String mgrno) {
        this.mgrno = mgrno;
    }

    @Id
    @Column(name = "`ADMRDEPT`", nullable = false, length = 3)
    public String getAdmrdept() {
        return this.admrdept;
    }

    public void setAdmrdept(String admrdept) {
        this.admrdept = admrdept;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vdept)) return false;
        final Vdept vdept = (Vdept) o;
        return Objects.equals(getDeptno(), vdept.getDeptno()) &&
                Objects.equals(getDeptname(), vdept.getDeptname()) &&
                Objects.equals(getMgrno(), vdept.getMgrno()) &&
                Objects.equals(getAdmrdept(), vdept.getAdmrdept());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDeptno(),
                getDeptname(),
                getMgrno(),
                getAdmrdept());
    }
}

