/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Vemplp generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`VEMPLP`")
@IdClass(VemplpId.class)
public class Vemplp implements Serializable {

    private String employeenumber;
    private String phonenumber;

    @Id
    @Column(name = "`EMPLOYEENUMBER`", nullable = false, length = 6)
    public String getEmployeenumber() {
        return this.employeenumber;
    }

    public void setEmployeenumber(String employeenumber) {
        this.employeenumber = employeenumber;
    }

    @Id
    @Column(name = "`PHONENUMBER`", nullable = true, length = 4)
    public String getPhonenumber() {
        return this.phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vemplp)) return false;
        final Vemplp vemplp = (Vemplp) o;
        return Objects.equals(getEmployeenumber(), vemplp.getEmployeenumber()) &&
                Objects.equals(getPhonenumber(), vemplp.getPhonenumber());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeenumber(),
                getPhonenumber());
    }
}

