/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Vempprojact generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`VEMPPROJACT`")
@IdClass(VempprojactId.class)
public class Vempprojact implements Serializable {

    private String empno;
    private String projno;
    private Short actno;
    private Float emptime;
    private Date emstdate;
    private Date emendate;

    @Id
    @Column(name = "`EMPNO`", nullable = false, length = 6)
    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    @Id
    @Column(name = "`PROJNO`", nullable = false, length = 6)
    public String getProjno() {
        return this.projno;
    }

    public void setProjno(String projno) {
        this.projno = projno;
    }

    @Id
    @Column(name = "`ACTNO`", nullable = false, scale = 0, precision = 5)
    public Short getActno() {
        return this.actno;
    }

    public void setActno(Short actno) {
        this.actno = actno;
    }

    @Id
    @Column(name = "`EMPTIME`", nullable = true, scale = 2, precision = 5)
    public Float getEmptime() {
        return this.emptime;
    }

    public void setEmptime(Float emptime) {
        this.emptime = emptime;
    }

    @Id
    @Column(name = "`EMSTDATE`", nullable = true)
    public Date getEmstdate() {
        return this.emstdate;
    }

    public void setEmstdate(Date emstdate) {
        this.emstdate = emstdate;
    }

    @Id
    @Column(name = "`EMENDATE`", nullable = true)
    public Date getEmendate() {
        return this.emendate;
    }

    public void setEmendate(Date emendate) {
        this.emendate = emendate;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vempprojact)) return false;
        final Vempprojact vempprojact = (Vempprojact) o;
        return Objects.equals(getEmpno(), vempprojact.getEmpno()) &&
                Objects.equals(getProjno(), vempprojact.getProjno()) &&
                Objects.equals(getActno(), vempprojact.getActno()) &&
                Objects.equals(getEmptime(), vempprojact.getEmptime()) &&
                Objects.equals(getEmstdate(), vempprojact.getEmstdate()) &&
                Objects.equals(getEmendate(), vempprojact.getEmendate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpno(),
                getProjno(),
                getActno(),
                getEmptime(),
                getEmstdate(),
                getEmendate());
    }
}

