/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class VempId implements Serializable {

    private String empno;
    private String firstnme;
    private String midinit;
    private String lastname;
    private String workdept;

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public String getFirstnme() {
        return this.firstnme;
    }

    public void setFirstnme(String firstnme) {
        this.firstnme = firstnme;
    }

    public String getMidinit() {
        return this.midinit;
    }

    public void setMidinit(String midinit) {
        this.midinit = midinit;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getWorkdept() {
        return this.workdept;
    }

    public void setWorkdept(String workdept) {
        this.workdept = workdept;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vemp)) return false;
        final Vemp vemp = (Vemp) o;
        return Objects.equals(getEmpno(), vemp.getEmpno()) &&
                Objects.equals(getFirstnme(), vemp.getFirstnme()) &&
                Objects.equals(getMidinit(), vemp.getMidinit()) &&
                Objects.equals(getLastname(), vemp.getLastname()) &&
                Objects.equals(getWorkdept(), vemp.getWorkdept());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpno(),
                getFirstnme(),
                getMidinit(),
                getLastname(),
                getWorkdept());
    }
}
