/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class VhdeptId implements Serializable {

    private String deptno;
    private String deptname;
    private String mgrno;
    private String admrdept;
    private String location;

    public String getDeptno() {
        return this.deptno;
    }

    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public String getMgrno() {
        return this.mgrno;
    }

    public void setMgrno(String mgrno) {
        this.mgrno = mgrno;
    }

    public String getAdmrdept() {
        return this.admrdept;
    }

    public void setAdmrdept(String admrdept) {
        this.admrdept = admrdept;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vhdept)) return false;
        final Vhdept vhdept = (Vhdept) o;
        return Objects.equals(getDeptno(), vhdept.getDeptno()) &&
                Objects.equals(getDeptname(), vhdept.getDeptname()) &&
                Objects.equals(getMgrno(), vhdept.getMgrno()) &&
                Objects.equals(getAdmrdept(), vhdept.getAdmrdept()) &&
                Objects.equals(getLocation(), vhdept.getLocation());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDeptno(),
                getDeptname(),
                getMgrno(),
                getAdmrdept(),
                getLocation());
    }
}
