/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Vphone generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`VPHONE`")
@IdClass(VphoneId.class)
public class Vphone implements Serializable {

    private String lastname;
    private String firstname;
    private String middleinitial;
    private String phonenumber;
    private String employeenumber;
    private String deptnumber;
    private String deptname;

    @Id
    @Column(name = "`LASTNAME`", nullable = false, length = 15)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Id
    @Column(name = "`FIRSTNAME`", nullable = false, length = 12)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Id
    @Column(name = "`MIDDLEINITIAL`", nullable = true, length = 1)
    public String getMiddleinitial() {
        return this.middleinitial;
    }

    public void setMiddleinitial(String middleinitial) {
        this.middleinitial = middleinitial;
    }

    @Id
    @Column(name = "`PHONENUMBER`", nullable = false, length = 4)
    public String getPhonenumber() {
        return this.phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    @Id
    @Column(name = "`EMPLOYEENUMBER`", nullable = false, length = 6)
    public String getEmployeenumber() {
        return this.employeenumber;
    }

    public void setEmployeenumber(String employeenumber) {
        this.employeenumber = employeenumber;
    }

    @Id
    @Column(name = "`DEPTNUMBER`", nullable = false, length = 3)
    public String getDeptnumber() {
        return this.deptnumber;
    }

    public void setDeptnumber(String deptnumber) {
        this.deptnumber = deptnumber;
    }

    @Id
    @Column(name = "`DEPTNAME`", nullable = false, length = 36)
    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vphone)) return false;
        final Vphone vphone = (Vphone) o;
        return Objects.equals(getLastname(), vphone.getLastname()) &&
                Objects.equals(getFirstname(), vphone.getFirstname()) &&
                Objects.equals(getMiddleinitial(), vphone.getMiddleinitial()) &&
                Objects.equals(getPhonenumber(), vphone.getPhonenumber()) &&
                Objects.equals(getEmployeenumber(), vphone.getEmployeenumber()) &&
                Objects.equals(getDeptnumber(), vphone.getDeptnumber()) &&
                Objects.equals(getDeptname(), vphone.getDeptname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLastname(),
                getFirstname(),
                getMiddleinitial(),
                getPhonenumber(),
                getEmployeenumber(),
                getDeptnumber(),
                getDeptname());
    }
}

