/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newfebproject.adventureworks2014.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class NewLineQueryResponse implements Serializable {

    @ColumnAlias("EmpId")
    private Integer empId;
    @ColumnAlias("FirstName")
    private String firstName;
    @ColumnAlias("LastName")
    private String lastName;
    @ColumnAlias("Salary")
    private Integer salary;
    @ColumnAlias("Address")
    private String address;

    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Integer getSalary() {
        return this.salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof NewLineQueryResponse)) return false;
        final NewLineQueryResponse newLineQueryResponse = (NewLineQueryResponse) o;
        return Objects.equals(getEmpId(), newLineQueryResponse.getEmpId()) &&
                Objects.equals(getFirstName(), newLineQueryResponse.getFirstName()) &&
                Objects.equals(getLastName(), newLineQueryResponse.getLastName()) &&
                Objects.equals(getSalary(), newLineQueryResponse.getSalary()) &&
                Objects.equals(getAddress(), newLineQueryResponse.getAddress());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpId(),
                getFirstName(),
                getLastName(),
                getSalary(),
                getAddress());
    }
}
